services:
   type: web
    name: server
    env: node
    runtime:
      version: '20'
    build:
      command: npm install
    start:
      command: npm run start
    ports:
      3000
    envVars:
    DB_HOST: ${DB_HOST}
    DB_PORT: ${DB_PORT}
    DB_USER: ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
    DB_NAME: ${DB_NAME}
    JWT_SECRET: ${JWT_SECRET}

    dependencies:
       mysql
       mysql2

      static:
       public
  
