services:
   type: web
    name: server
    env: node
    runtime:
      version: '20'
    build:
      command: npm install && npm run build

    start:
      command: npm run start
    ports:
      3000
    envVars:
       key: DB_HOST
        value: ${DB_HOST}
       key: DB_PORT
        value: ${DB_PORT}
       key: DB_USER
        value: ${DB_USER}
       key: DB_PASSWORD
        value: ${DB_PASSWORD}
       key: DB_NAME
        value: ${DB_NAME}
       key: JWT_SECRET
        value: ${JWT_SECRET}


    dependencies:
       mysql
       mysql2

      static:
       public
  
